name: flutter_test_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  get: ^4.7.2
  dio: ^5.8.0+1
  freezed_annotation: ^2.4.4
  equatable: ^2.0.7
  json_annotation: ^4.8.1
  shimmer: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

  mockito: ^5.4.4
  build_runner: ^2.4.13
  freezed: ^2.5.7
  json_serializable: ^6.7.1
  

flutter:
  uses-material-design: true
  assets:
    - assets/mock_data.json